### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by ghost** [swathysubhash/docprint#2]
When I try to run the command line tool I always get this error:

```
$ docprint -p index.md -d docs
TypeError: Cannot read property 'find' of undefined
    at setHost (/usr/local/lib/node_modules/docprint/src/index.js:76:22)
    at module.exports (/usr/local/lib/node_modules/docprint/src/index.js:43:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/docprint/bin/index.js:15:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7) 'TypeError: Cannot read property \'find\' of undefined\n    at setHost (/usr/local/lib/node_modules/docprint/src/index.js:76:22)\n    at module.exports (/usr/local/lib/node_modules/docprint/src/index.js:43:5)\n    at Object.<anonymous> (/usr/local/lib/node_modules/docprint/bin/index.js:15:18)\n    at Module._compile (module.js:571:32)\n    at Object.Module._extensions..js (module.js:580:10)\n    at Module.load (module.js:488:32)\n    at tryModuleLoad (module.js:447:12)\n    at Function.Module._load (module.js:439:3)\n    at Module.runMain (module.js:605:10)\n    at run (bootstrap_node.js:425:7)'
```

For any input file. My `node` version is 7.7.3.

**Comment by swathysubhash** [comment]
Fixed
